[mcp_servers.idea]
command = "C:\\Program Files\\JetBrains\\IntelliJ IDEA 2026.2\\bin\\idea64.exe"
args = ["stdioMcpServer"]
env = {
    IJ_MCP_SERVER_PROJECT_PATH = "C:/Users/lionheart/IdeaProjects/debezium-server-ducklake",
    IJ_MCP_SERVER_PORT = "64342",
}
startup_timeout_sec = 30
